### ISSUE TITLE
Success check in M2MNsdlInterface::create_nsdl_list_structure() checks only success of last call to create_nsdl_structure()

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-cloud-client#14]
success is assigned multiple times at
https://github.com/ARMmbed/mbed-cloud-client/blob/9b0bc6a2f3f1f5dbb5be1827db83004d531b99c9/mbed-client/source/m2mnsdlinterface.cpp#L375

There is no early return on fail. Thus only the last assignment will be returned. This assumes that all following calls after an initial fail will always fail. Was not the case in our codebase.

**Comment by markus-becker-tridonic-com** [comment]
FYI: @MarceloSalazar @karsev

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2906

**Comment by anttiylitokola** [comment]
Thanks for your report. This has now been fixed and the change will be available in next release.
