### ISSUE TITLE
Client does not report running out of memory

### ISSUE THREAD

**Issue by paul-szczepanek-arm** [ARMmbed/mbed-cloud-client#16]
There a lot of naked mallocs in the application that either don't check the result or report a generic error and give no indication that the application has ran out of memory. This needs to be fixed and out of memory errors need to be propagated and reported.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3014

**Comment by JanneKiiskila** [comment]
Thank you for the feedback, this has been fixed and will be included to the next release (2.2.0).

**Comment by teetak01** [comment]
This has been improved in 2.2.0. If you have further issues, please open a new ticket witha more  specific description.
