### ISSUE TITLE
Release Benchmarks

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-cloud-client#49]
Can we get RAM/Flash consumption benchmarks with each release of the client?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3560

**Comment by teetak01** [comment]
We can start making those regular as part of at least major/minor releases.

**Comment by JanneKiiskila** [comment]
Numbers are published in here (for latest release, no intention of keeping a history - but the docs are versioned, so one can shuffle back) https://www.pelion.com/docs/device-management/current/cloud-requirements/requirements-for-production-devices.html

**Comment by 40Grit** [comment]
That should be sufficient.

However, it would also be beneficial if there were a repository for the documentation sources.

It would be good to have a place to track issues from the community/partners for the docs.

Additionally the diffs between doc releases are much more apparent when viewed from source in github or other git interface.


Even if the doc source releases came squashed similar to the client releases.

**Comment by JanneKiiskila** [comment]
@iriark01  @peknis01  @melwee01 - note the feedback on docs.

**Comment by JanneKiiskila** [comment]
@40Grit  - docs issues can be raised also here as issues, no problem in that.

**Comment by melwee01** [comment]
Noted.

**Comment by iriark01** [comment]
The repo is private by request of Product.

**Comment by loverdeg-ep** [comment]
@iriark01 Could it at least be opened up to partners in some form?

**Comment by iriark01** [comment]
That's a product decision. Janne can decide with them, and I'll happily open it (them - there's more than one repo)
