### ISSUE TITLE
Pin this repository to top of ARMmbed Group

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-cloud-client#51]
There is an open space at the top of the ARMmbed group. I think this repository ought to be pinned there.

![image](https://user-images.githubusercontent.com/24318071/63712179-23a93d00-c80b-11e9-9f6d-08090f645d8e.png)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3602

**Comment by MarceloSalazar** [comment]
Done

**Comment by JanneKiiskila** [comment]
Thanks @MarceloSalazar ! Thank you for the feedback @loverdeg-ep .
