### ISSUE TITLE
Building .a library

### ISSUE THREAD

**Issue by chuayk** [ARMmbed/mbed-cloud-client#54]
What are the steps to build a .a library from this?
So that I can just -lmbed or something in the Linker flags

Target: x86_64 Generic Linux

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3807

**Comment by teetak01** [comment]
Hi @chuayk 

You can take a look to our linux tutorial which uses CMake. This requires the application also.

https://www.pelion.com/docs/device-management/current/connecting/linux-on-pc.html

**Comment by JanneKiiskila** [comment]
Hi @chuayk 

Please confirm your issue or sorted or provide more details. We will close ticket in a week, if no further responses are received.
