### ISSUE TITLE
client-lite public release

### ISSUE THREAD

**Issue by Alex-EEE** [ARMmbed/mbed-cloud-client#56]
Any update on when client lite will be publicly available?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3878

**Comment by JanneKiiskila** [comment]
We are working on it full speed, hoping to have it out before Christmas but can't guarantee that. If it slips Christmas then it will slip to mid January, 2020. The 1st release will be an Alpha release, so it will not be production quality - we will however accept issues & feedback to guide our development.

**Comment by ghseb** [comment]
Is there any news on this topic? A light client definitely makes sense for very constrained devices.

**Comment by JanneKiiskila** [comment]
Things rarely go as planned, it seems - but we're in the last finalization steps of the release process. Alpha release will be out this week. Memory targets we have will not be met with this release though, some more squeezing to be done (mainly the MbedTLS side).

**Comment by JanneKiiskila** [comment]
Hi @Alex-EEE 

Client Lite Alpha 1.0 release is now officially out - please see [docs](https://www.pelion.com/docs/pelion-client-lite/v1.0/introduction/index.html) and [Client Lite example](https://github.com/ARMmbed/pelion-client-lite-example).
